{{- if .Values.global.istio.enabled }}
# License terms and conditions:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Service
metadata:
    name: {{ include "auth-server-key-rotation.fullname" . }}
    labels:
{{ include "auth-server-key-rotation.labels" . | indent 6 }}
spec:
    ports:
        - name: http
          port: 80
          targetPort: 8080
    selector:
        app: {{ .Release.Name }}-{{ include "auth-server-key-rotation.name" . }}
    type: ClusterIP
{{- end }}