# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "1.0.0-a4"
home: https://jans.io
maintainers:
- name: Janssen

description: Helm chart for SCIM
name: scim
version: 1.0.0-a4
