# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: scim
version: 5.0.0
kubeVersion: ">=v1.17.0-0"
description: System for Cross-domain Identity Management (SCIM) version 2.0
type: application
keywords:
  - SCIM
  - API
home: https://jans.io
sources:
  - https://github.com/JanssenProject/jans-scim
  - https://jans.io/api-guide/scim-api/
  - https://github.com/JanssenProject/docker-jans-scim
  - https://github.com/JanssenFederation/cloud-native-edition/tree/master/pyjans/kubernetes/templates/helm/jans/charts/scim
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://jans.io/favicon.ico
appVersion: "5.0.0"
