apiVersion: v2
name: link
version: 2.0.0
kubeVersion: ">=v1.22.0-0"
description: Jans Link
type: application
keywords:
  - link
home: https://jans.io
sources:
  - https://github.com/JanssenProject/jans/jans-link
  - https://github.com/JanssenProject/jans/docker-jans-link
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/assets/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "2.0.0"
