kubeVersion: ">=v1.17.0-0"
annotations:
  artifacthub.io/changes: |
    - Janssen 1.0 under dev charts
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: auth-server
      image: janssenproject/auth-server:1.0.0_dev
    - name: auth-server-key-rotation
      image: janssenproject/certmanager:1.0.0_dev
    - name:  client-api
      image: janssenproject/client-api:1.0.0_dev
    - name: configuration-manager
      image: janssenproject/configuration-manager:1.0.0_dev
    - name:  config-api
      image: janssenproject/config-api:1.0.0_dev
    - name: fido2
      image: janssenproject/fido2:1.0.0_dev
    - name: opendj
      image: gluufederation/opendj:5.0.0_dev
    - name: persistence
      image: janssenproject/persistence-loader:1.0.0_dev
    - name: scim
      image: janssenproject/scim:1.0.0_dev
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "true"
apiVersion: v2
appVersion: "1.0.0-b9"
icon: https://avatars.githubusercontent.com/u/68292770?s=200&v=4
home: https://github.com/JanssenProject/jans-cloud-native
sources:
- https://jans.io
- https://github.com/JanssenProject/jans-cloud-native
maintainers:
- name: moabu
  email: support@gluu.org
description: Janssen Access and Identity Management
name: jans
version: 1.0.0-b9
dependencies:
- name: config
  condition: global.config.enabled
  version: 1.0.0-b9
  repository: ""

- name: config-api
  condition: global.config-api.enabled
  version: 1.0.0-b9
  repository: ""

- name: opendj
  condition: global.opendj.enabled
  version: 1.0.0-b9
  repository: ""

- name: auth-server
  condition: global.auth-server.enabled
  version: 1.0.0-b9
  repository: ""

- name: fido2
  condition: global.fido2.enabled
  version: 1.0.0-b9
  repository: ""

- name: scim
  condition: global.scim.enabled
  version: 1.0.0-b9
  repository: ""

- name: nginx-ingress
  condition: global.nginx-ingress.enabled
  version: 1.0.0-b9
  repository: ""

- name: auth-server-key-rotation
  condition: global.auth-server-key-rotation.enabled
  version: 1.0.0-b9
  repository: ""

- name: client-api
  condition: global.client-api.enabled
  version: 1.0.0-b9
  repository: ""

- name: persistence
  condition: global.persistence.enabled
  version: 1.0.0-b9
  repository: ""

- name: cn-istio-ingress
  condition: global.istio.ingress
  version: 1.0.0-b9
  repository: ""
