# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# opendj Environament Variables
nameOverride: ""
fullnameOverride: ""
# StatefulSet
# values declaration
multiCluster:
  enabled: false
  serfAdvertiseAddr: "demoexample.gluu.org:31946"
  #The key size must be a 16, 24, or 32 bytes encoded as base64 string.
  serfKey: Z51b6PgKU1MZ75NCZOTGGoc0LP2OF3qvF6sjxHyQCYk=
  # Json for serf Peers
  serfPeers: ["firstldap.jans.io:30946", "secondldap.jans.io:31946"]
replicas: 1
service:
  ldapServiceName: opendj
image:
  repository: gluufederation/opendj
  tag: 5.0.0_dev
  pullPolicy: Always

persistence:
  size: 5Gi
  accessModes: ReadWriteOnce
  type: DirectoryOrCreate

#servicePorts values used in StatefulSet container
ports:
  tcp-ldaps:
    port: 1636
    targetPort: 1636
    protocol: TCP
    # Used when multiCluster.enabled is set to true
    nodePort: 30636
  tcp-ldap:
    port: 1389
    targetPort: 1389
    protocol: TCP
    # Used when multiCluster.enabled is set to true
    nodePort: 30389
  tcp-repl:
    port: 8989
    targetPort: 8989
    protocol: TCP
    # Used when multiCluster.enabled is set to true
    nodePort: 30989
  tcp-admin:
    port: 4444
    targetPort: 4444
    protocol: TCP
    # Used when multiCluster.enabled is set to true
    nodePort: 30444
  tcp-serf:
    port: 7946
    targetPort: 7946
    protocol: TCP
    # Used when multiCluster.enabled is set to true
    nodePort: 30946
  udp-serf:
    port: 7946
    targetPort: 7946
    protocol: UDP
    # Used when multiCluster.enabled is set to true
    nodePort: 30946
# VolumeMounts for StatefulSet
# opendj-init vm
volumeMounts:
  config:
    mountPath: /opt/opendj/config
    name: opendj-volume
  ldif: 
    mountPath: /opt/opendj/ldif
    name: opendj-volume
  logs: 
    mountPath: /opt/opendj/logs
    name: opendj-volume
  db: 
    mountPath: /opt/opendj/db
    name: opendj-volume
  flag: 
    mountPath: /flag
    name: opendj-volume
