[[disallowed-methods]]
path = "uuid7::uuid7"
reason = "not allowed method in WASM, use cedarling::log::log_entry::gen_uuid7()"

[[disallowed-methods]]
path = "std::time::SystemTime::now"
reason = "may not work correctly in WASM, use chrono::Utc::now() instead"
