CEDARLING_APPLICATION_NAME: My App
CEDARLING_POLICY_STORE_URI: ""
CEDARLING_POLICY_STORE_ID: "840da5d85403f35ea76519ed1a18a33989f855bf1cf8"
CEDARLING_LOG_TYPE: "memory"
CEDARLING_LOG_LEVEL: "DEBUG"
CEDARLING_LOG_TTL: 60
CEDARLING_USER_AUTHZ: "enabled"
CEDARLING_WORKLOAD_AUTHZ: "enabled"
CEDARLING_PRINCIPAL_BOOLEAN_OPERATION:
  and:
    - "===":
        - var: "Jans::Workload"
        - "ALLOW"
    - "===":
        - var: "Jans::User"
        - "ALLOW"
CEDARLING_LOCAL_JWKS: null
CEDARLING_POLICY_STORE_LOCAL: null
CEDARLING_POLICY_STORE_LOCAL_FN: "../config/policy-store.json"
CEDARLING_JWT_SIG_VALIDATION: "enabled"
CEDARLING_JWT_STATUS_VALIDATION: "disabled"
CEDARLING_JWT_SIGNATURE_ALGORITHMS_SUPPORTED:
  - "HS256"
  - "RS256"
CEDARLING_ID_TOKEN_TRUST_MODE: "strict"
CEDARLING_LOCK: "disabled"
CEDARLING_LOCK_SERVER_CONFIGURATION_URI: null
CEDARLING_LOCK_DYNAMIC_CONFIGURATION: "disabled"
CEDARLING_LOCK_HEALTH_INTERVAL: 0
CEDARLING_LOCK_TELEMETRY_INTERVAL: 0
CEDARLING_LOCK_LISTEN_SSE: "disabled"
CEDARLING_MAX_DEFAULT_ENTITIES: 1000
CEDARLING_MAX_BASE64_SIZE: 1048576
