
apiVersion: v2
name: config
version: 1.0.6-dev
kubeVersion: ">=v1.21.0-0"
description: Configuration parameters for setup and initial configuration secret and config layers used by Janssen services.
type: application
keywords:
  - configuration
  - secrets
home: /docker-jans-configurator
sources:
  - /docker-jans-configurator
  - https://github.com/JanssenProject/jans/docker-jans-configurator
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/assets/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.0.6-dev"
