# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: config
version: 1.0.0-beta.14
kubeVersion: ">=v1.21.0-0"
description: Configuration parameters for setup and initial configuration secret and config layers used by Janssen services.
type: application
keywords:
  - configuration
  - secrets
home: https://github.com/JanssenProject/jans/docker-jans-configurator
sources:
  - https://github.com/JanssenProject/jans/docker-jans-configurator
  - https://github.com/JanssenProject/jans/docker-jans-configurator
  - https://github.com/JanssenFederation/flex/tree/main/flex-cn-setup/pyjanssen/kubernetes/templates/helm/janssen/charts/config
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://jans.io/favicon.ico
appVersion: "1.0.0"
