apiVersion: v2
name: saml
version: 1.4.0
kubeVersion: ">=v1.21.0-0"
description: Jans SAML
type: application
keywords:
  - SAML
  - Keycloak
home: https://jans.io
sources:
  - https://github.com/JanssenProject/jans/docker-jans-saml
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/assets/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.4.0"
