kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: client-api-policy
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: client-api
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: casa
    ports:
    - protocol: TCP
      port: 8443
  - from:
    - podSelector:
        matchLabels:
          app: auth-server
    ports:
    - protocol: TCP
      port: 8443
  - from:
    - namespaceSelector:
        matchLabels:
          app: ingress-kong
    - podSelector:
        matchLabels:
          app: ingress-kong
    ports:
    - protocol: TCP
      port: 8443