
apiVersion: v2
name: auth-server
version: 1.0.8-dev
kubeVersion: ">=v1.21.0-0"
description: OAuth Authorization Server, the OpenID Connect Provider, the UMA Authorization Server--this is the main Internet facing component of Janssen. It's the service that returns tokens, JWT's and identity assertions. This service must be Internet facing.
type: application
keywords:
  - Authorization
  - OpenID
home: https://jans.io
sources:
  - https://github.com/JanssenProject/jans-auth-server
  - https://github.com/JanssenProject/docker-jans-auth-server
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/assets/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.0.8-dev"
