# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: auth-server-key-rotation
version: 1.0.0-b9
kubeVersion: ">=v1.17.0-0"
description: Responsible for regenerating auth-keys per x hours
type: application
keywords:
  - Auth keys Rotation
home: https://jans.io
sources:
  - https://github.com/JanssenProject/docker-jans-certmanager
  - https://github.com/JanssenFederation/cloud-native-edition/tree/master/pyjans/kubernetes/templates/helm/jans/charts/auth-server-key-rotation
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://jans.io/favicon.ico
appVersion: "1.0.0-b9"