# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: opendj
version: 5.0.0
kubeVersion: ">=v1.19.0-0"
description: OpenDJ is a directory server which implements a wide range of Lightweight Directory Access Protocol and related standards, including full compliance with LDAPv3 but also support for Directory Service Markup Language (DSMLv2).Written in Java, OpenDJ offers multi-master replication, access control, and many extensions.
type: application
keywords:
  - LDAP
  - OpenDJ
home: https://jans.io
sources:
  - https://github.com/JanssenFederation/docker-opendj
  - https://github.com/JanssenFederation/cloud-native-edition/tree/master/pyjans/kubernetes/templates/helm/jans/charts/opendj
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://jans.io/favicon.ico
appVersion: "5.0.0"