
apiVersion: v2
name: opendj
version: 5.0.4
kubeVersion: ">=v1.21.0-0"
description: OpenDJ is a directory server which implements a wide range of Lightweight Directory Access Protocol and related standards, including full compliance with LDAPv3 but also support for Directory Service Markup Language (DSMLv2).Written in Java, OpenDJ offers multi-master replication, access control, and many extensions.
type: application
keywords:
  - LDAP
  - OpenDJ
home: https://jans.io
sources:
  - https://github.com/JanssenFederation/docker-opendj
  - https://github.com/JanssenFederation/flex/tree/main/flex-cn-setup/pyjanssen/kubernetes/templates/helm/janssen/charts/opendj
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.0.0"