# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: fido2
version: 1.0.0-b8
kubeVersion: ">=v1.17.0-0"
description: FIDO 2.0 (FIDO2) is an open authentication standard that enables leveraging common devices to authenticate to online services in both mobile and desktop environments.
type: application
keywords:
  - fido2
  - u2f
home: https://jans.io/
sources:
  - https://jans.io/
  - https://github.com/JanssenProject/jans-fido2
  - https://github.com/JanssenProject/docker-jans-fido2
  - https://github.com/JanssenFederation/cloud-native-edition/tree/master/pyjans/kubernetes/templates/helm/jans/charts/fido2
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://jans.io/favicon.ico
appVersion: "1.0.0-b8"
