# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "1.0.0-a3"
home: https://jans.io
maintainers:
- name: jans
email: support@jans.io
description: A Helm chart for Janssen server
name: config
version: 1.0.0-a3
