# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: auth-server
version: 5.0.0
kubeVersion: ">=v1.17.0-0"
description: OAuth Authorization Server, the OpenID Connect Provider, the UMA Authorization Server--this is the main Internet facing component of Janssen. It's the service that returns tokens, JWT's and identity assertions. This service must be Internet facing.
type: application
keywords:
  - Autherization
  - OpenID
home: https://jans.io
sources:
  - https://github.com/JanssenProject/jans-auth-server
  - https://github.com/JanssenProject/docker-jans-auth-server
  - https://github.com/JanssenFederation/cloud-native-edition/tree/master/pyjans/kubernetes/templates/helm/jans/charts/auth-server
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://jans.io/favicon.ico
appVersion: 5.0.0
