apiVersion: v1
entries:
  janssen:
  - annotations:
      artifacthub.io/changes: |
        - Update always
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/images: |
        - name: auth-server
          image: janssenproject/auth-server:1.0.0-beta.16
        - name: auth-server-key-rotation
          image: janssenproject/certmanager:1.0.0-beta.16
        - name:  client-api
          image: janssenproject/client-api:1.0.0-beta.16
        - name: configuration-manager
          image: janssenproject/configurator:1.0.0-beta.16
        - name:  config-api
          image: janssenproject/config-api:1.0.0-beta.16
        - name: fido2
          image: janssenproject/fido2:1.0.0-beta.16
        - name: opendj
          image: gluufederation/opendj:5.0.0_dev
        - name: persistence
          image: janssenproject/persistence-loader:1.0.0-beta.16
        - name: scim
          image: janssenproject/scim:1.0.0-beta.16
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "true"
      catalog.cattle.io/certified: partner
      catalog.cattle.io/display-name: Janssen Cloud Identity and Access Management
      catalog.cattle.io/release-name: janssen
    apiVersion: v2
    appVersion: 1.0.0
    created: "2022-05-06T11:08:20.426079385Z"
    dependencies:
    - condition: global.config.enabled
      name: config
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.config-api.enabled
      name: config-api
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.opendj.enabled
      name: opendj
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.auth-server.enabled
      name: auth-server
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.fido2.enabled
      name: fido2
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.scim.enabled
      name: scim
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.nginx-ingress.enabled
      name: nginx-ingress
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.auth-server-key-rotation.enabled
      name: auth-server-key-rotation
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.client-api.enabled
      name: client-api
      repository: ""
      version: 1.0.0-beta.16
    - condition: global.persistence.enabled
      name: persistence
      repository: ""
      version: 1.0.0-beta.16
    description: Janssen Access and Identity Management
    digest: 0df49415e53b2256f81677e3f46d644827dc9c73a50967c9b2d710eb47e2da86
    home: https://jans.io
    icon: https://github.com/JanssenProject/jans/raw/main/docs/logo/janssen_project_favicon_transparent_50px_50px.png
    kubeVersion: '>=v1.21.0-0'
    maintainers:
    - email: support@jans.io
      name: moabu
    name: janssen
    sources:
    - https://jans.io
    - https://github.com/JanssenProject/jans/charts/janssen
    urls:
    - janssen-1.0.0-beta.16.tgz
    version: 1.0.0-beta.16
generated: "2022-05-06T11:08:20.414542517Z"
