[package]
name = "cedarling"
authors = ["Newton Toto <nyachiengatoto@gmail.com>"]
publish = false
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jsonwebtoken = "9.3.0"
cedar-policy = { version = "3.2.0", features = ["wasm"] }
miniz_oxide = { version = "0.7.4", default-features = false, features = [
	"with-alloc",
] }

# serde
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"

# Environment Dependencies
console_error_panic_hook = "0.1.7"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"

[dependencies.web-sys]
version = "0.3.69"
features = [
	'console',
	'Response',
	'Request',
	'Headers',
	'RequestMode',
	'RequestInit',
	'EventSource',
	'MessageEvent',
	'Url',
	'UrlSearchParams',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
