[package]
name = "cedarling"
authors = ["Newton Toto <nyachiengatoto@gmail.com>"]
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
cedar-policy = { version = "3.2.0", features = ["wasm"] }
console_error_panic_hook = "0.1.7"
serde = { version = "*", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
static-toml = "1.2.0"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"

[dependencies.web-sys]
version = "0.3.69"
features = [
	'console',
	'Window',
	'Response',
	'Request',
	'Headers',
	'RequestMode',
	'RequestInit',
	'EventSource',
	'MessageEvent'
]

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
