
apiVersion: v2
name:  cn-istio-ingress
version: 1.5.0
kubeVersion: ">=v1.21.0-0"
description: Istio Gateway
type: application
keywords:
  - istio
  - gateway
home: https://jans.io
sources:
  - https://docs.jans.io/
  - https://github.com/JanssenProject/jans/tree/main/charts/janssen/charts/cn-istio-ingress
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/assets/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.5.0"
