{{- if .Values.global.istio.enabled }}
# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-istio-auth-server
  namespace: {{.Release.Namespace}}
spec:
  hosts:
  - {{ .Values.global.fqdn }}
  gateways:
  - {{ .Release.Name }}-global-gtw # can omit the namespace if gateway is in same namespace as virtual service.
  http:
  - name: "{{ .Release.Name }}-istio-openid-config"
    match:
    - uri:
        prefix: "/.well-known/openid-configuration"
    rewrite:
      uri: "/auth-server/.well-known/openid-configuration"
    route:
      - destination:
          host: {{ index .Values "global" "auth-server" "authServerServiceName" }}.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 8080
        weight: 100
  - name: "{{ .Release.Name }}-istio-uma2-config"
    match:
    - uri:
        prefix: "/.well-known/uma2-configuration"
    rewrite:
      uri: "/auth-server/restv1/uma2-configuration"
    route:
      - destination:
          host: {{ index .Values "global" "auth-server" "authServerServiceName" }}.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 8080
        weight: 100
  - name: "{{ .Release.Name }}-istio-webdiscovery"
    match:
    - uri:
        prefix: "/.well-known/simple-web-discovery"
    rewrite:
      uri: "/auth-server/.well-known/simple-web-discovery"
    route:
    - destination:
        host: {{ index .Values "global" "auth-server" "authServerServiceName" }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
      weight: 100
  - name: "{{ .Release.Name }}-istio-cn"
    match:
    - uri:
        prefix: "/auth-server"
    route:
    - destination:
        host: {{ index .Values "global" "auth-server" "authServerServiceName" }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
  - name: "{{ .Release.Name }}-istio-webfinger"
    match:
    - uri:
        prefix: "/.well-known/webfinger"
    rewrite:
      uri: "/auth-server/.well-known/webfinger"
    route:
    - destination:
        host: {{ index .Values "global" "auth-server" "authServerServiceName" }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
      weight: 100
  - name: "{{ .Release.Name }}-istio-u2f-config"
    match:
    - uri:
        prefix: "/.well-known/fido-configuration"
    rewrite:
      uri: "/auth-server/restv1/fido-configuration"
    route:
    - destination:
        host: {{ index .Values "global" "auth-server" "authServerServiceName" }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
      weight: 100
{{- end }}