
apiVersion: v1
kind: Service
metadata:
  # the name must match the application
  name: {{ index .Values "global" "client-api" "clientApiServerServiceName" }}
  namespace: {{ .Release.Namespace }}
  labels:
    APP_NAME: client-api
{{ include "client-api.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - port: 8444
      name: tcp-{{ include "client-api.name" . }}-admin-gui
    - port: 8443
      name: tcp-{{ include "client-api.name" . }}-app-connector
  selector:
    app: {{ .Release.Name }}-{{ include "client-api.name" . }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
{{ toYaml . | indent 4 }}
  {{- end }}
