
apiVersion: v2
name: nginx-ingress
version: 5.0.4
kubeVersion: ">=v1.21.0-0"
description: Nginx ingress definitions chart
type: application
keywords:
  - nginx
  - ingress
home: https://jans.io
sources:
  - https://github.com/kubernetes/ingress-nginx
  - https://kubernetes.io/docs/concepts/services-networking/ingress/
  - https://github.com/JanssenFederation/flex/tree/main/flex-cn-setup/pyjanssen/kubernetes/templates/helm/janssen/charts/nginx-ingress
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.0.0"
