
apiVersion: v2
name: nginx-ingress
version: 1.0.7-dev
kubeVersion: ">=v1.21.0-0"
description: Nginx ingress definitions chart
type: application
keywords:
  - nginx
  - ingress
home: https://jans.io
sources:
  - https://github.com/kubernetes/ingress-nginx
  - https://kubernetes.io/docs/concepts/services-networking/ingress/
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/assets/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.0.7-dev"
