# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "1.0.0-a4"
description: A Helm chart for persistence layer for Janssen server
name: persistence
version: 1.0.0-a4
maintainers:
- name: Janssen

home: https://jans.io
