# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "1.0.0-b7"
description: nginx-ingress chart
name: nginx-ingress
version: 1.0.0-b7
maintainers:
- name: moabu
  email: mo@gluu.org

home: https://jans.io