# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: client-api
version: 1.0.0-b8
kubeVersion: ">=v1.17.0-0"
description: Middleware API to help application developers call an OAuth, OpenID or UMA server. You may wonder why this is necessary. It makes it easier for client developers to use OpenID signing and encryption features, without becoming crypto experts. This API provides some high level endpoints to do some of the heavy lifting.
type: application
keywords:
  - client
  - API
home: https://jans.org/docs/oxd
sources:
  - https://github.com/JanssenProject/jans-client-api
  - https://github.com/JanssenProject/docker-jans-client-api
  - https://github.com/JanssenFederation/cloud-native-edition/tree/master/pyjans/kubernetes/templates/helm/jans/charts/client-api
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://jans.io/favicon.ico
appVersion: "1.0.0-b8"
