
apiVersion: v2
name: fido2
version: 1.0.8-dev
kubeVersion: ">=v1.21.0-0"
description: FIDO 2.0 (FIDO2) is an open authentication standard that enables leveraging common devices to authenticate to online services in both mobile and desktop environments.
type: application
keywords:
  - fido2
  - u2f
home: https://jans.io/
sources:
  - https://jans.io/
  - https://github.com/JanssenProject/jans/jans-fido2
  - https://github.com/JanssenProject/jans/docker-jans-fido2
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/assets/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.0.8-dev"
