# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Service
metadata:
  # the name must match the application
  name: {{ index .Values "global" "config-api" "configApiServerServiceName" }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "config-api.labels" . | indent 4 }}
spec:
  ports:
    - port: 9444
      name: tcp-{{ include "config-api.name" . }}-ssl
    - port: 8074
      name: tcp-{{ include "config-api.name" . }}-http
  selector:
    app: {{ .Release.Name }}-{{ include "config-api.name" . }}