global:
  istio:
    ingress: false
    enabled: false
    namespace: istio-system
  alb:
    ingress: false
  cloud:
    testEnviroment: false
  upgrade:
    enabled: false
  provisioner: microk8s.io/hostpath
  pool: default
  fsType: ext4
  gcePdStorageType: pd-standard
  azureStorageAccountType: Standard_LRS
  azureStorageKind: Managed
  reclaimPolicy: Retain
  lbIp: ""
  domain: demoexample.jans.io
  isDomainRegistered: "false"
  cnPersistenceType: ldap
  auth-server:
    enabled: true
  fido2:
    enabled: true
  scim:
    enabled: true
  config:
    enabled: true
  config-api:
    enabled: true
  persistence:
    enabled: true
  opendj:
    enabled: true
  client-api:
    enabled: true
  nginx-ingress:
    enabled: true
  auth-server-key-rotation:
    enabled: true
config:
  orgName: Janssen
  email: support@jans.com
  adminPass: P@ssw0rd
  ldapPass: P@ssw0rd
  redisPass: P@assw0rd
  countryCode: US
  state: TX
  city: Austin
  secondaryCluster:
    enabled: false
  configmap:
    cnConfigKubernetesConfigMap: cn
    cnSecretKubernetesSecret: cn
    cnClientApiApplicationCertCn: client-api
    cnClientApiAdminCertCn: client-api
    cnCouchbaseCrt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lKQUwyem5UWlREUHFNTUEwR0NTcUdTSWIzRFFFQkN3VUFNQzB4S3pBcEJnTlYKQkFNTUlpb3VZMkpuYkhWMUxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NakF3TWpBMQpNRGt4T1RVeFdoY05NekF3TWpBeU1Ea3hPVFV4V2pBdE1Tc3dLUVlEVlFRRERDSXFMbU5pWjJ4MWRTNWtaV1poCmRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFycmQ5T3lvSnRsVzhnNW5nWlJtL2FKWjJ2eUtubGU3dVFIUEw4Q2RJa1RNdjB0eHZhR1B5UkNQQgo3RE00RTFkLzhMaU5takdZZk41QjZjWjlRUmNCaG1VNmFyUDRKZUZ3c0x0cTFGT3MxaDlmWGo3d3NzcTYrYmlkCjV6Umw3UEE0YmdvOXVkUVRzU1UrWDJUUVRDc0dxVVVPWExrZ3NCMjI0RDNsdkFCbmZOeHcvYnFQa2ZCQTFxVzYKVXpxellMdHN6WE5GY0dQMFhtU3c4WjJuaFhhUGlva2pPT2dyMkMrbVFZK0htQ2xGUWRpd2g2ZjBYR0V0STMrKwoyMStTejdXRkF6RlFBVUp2MHIvZnk4TDRXZzh1YysvalgwTGQrc2NoQTlNQjh3YmJORUp2ZjNMOGZ5QjZ0cTd2CjF4b0FnL0g0S1dJaHdqSEN0dFVnWU1oU0xWV3UrUUlEQVFBQm80R2NNSUdaTUIwR0ExVWREZ1FXQkJTWmQxWU0KVGNIRVZjSENNUmp6ejczZitEVmxxREJkQmdOVkhTTUVWakJVZ0JTWmQxWU1UY0hFVmNIQ01Sanp6NzNmK0RWbApxS0V4cEM4d0xURXJNQ2tHQTFVRUF3d2lLaTVqWW1kc2RYVXVaR1ZtWVhWc2RDNXpkbU11WTJ4MWMzUmxjaTVzCmIyTmhiSUlKQUwyem5UWlREUHFNTUF3R0ExVWRFd1FGTUFNQkFmOHdDd1lEVlIwUEJBUURBZ0VHTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQk9meTVWSHlKZCtWUTBXaUQ1aSs2cmhidGNpSmtFN0YwWVVVZnJ6UFN2YWVFWQp2NElVWStWOC9UNnE4Mk9vVWU1eCtvS2dzbFBsL01nZEg2SW9CRnVtaUFqek14RTdUYUhHcXJ5dk13Qk5IKzB5CnhadG9mSnFXQzhGeUlwTVFHTEs0RVBGd3VHRlJnazZMRGR2ZEN5NVdxWW1MQWdBZVh5VWNaNnlHYkdMTjRPUDUKZTFiaEFiLzRXWXRxRHVydFJrWjNEejlZcis4VWNCVTRLT005OHBZN05aaXFmKzlCZVkvOEhZaVQ2Q0RRWWgyTgoyK0VWRFBHcFE4UkVsRThhN1ZLL29MemlOaXFyRjllNDV1OU1KdjM1ZktmNUJjK2FKdWduTGcwaUZUYmNaT1prCkpuYkUvUENIUDZFWmxLaEFiZUdnendtS1dDbTZTL3g0TklRK2JtMmoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    cnCouchbasePass: P@ssw0rd
    cnCouchbaseSuperUserPass: P@ssw0rd
    cnCouchbaseSuperUser: admin
    cnCouchbaseUrl: cbjans.default.svc.cluster.local
    cnCouchbaseIndexNumReplica: 0
    cnCouchbaseUser: jans
    cnCouchbasePassFile: /etc/jans/conf/couchbase_password
    cnCouchbaseSuperUserPassFile: /etc/jans/conf/couchbase_superuser_password
    cnCouchbaseCertFile: /etc/certs/couchbase.crt
    cnPersistenceLdapMapping: default
    cnCacheType: NATIVE_PERSISTENCE
    cnMaxRamPercent: "75.0"
    configAdapterName: kubernetes
    containerMetadataName: kubernetes
    configSecretAdapter: kubernetes
    cnRedisUrl: redis:6379
    cnRedisUseSsl: "false"
    cnRedisType: STANDALONE
    cnRedisSslTruststore: ""
    cnRedisSentinelGroup: ""
    cnAuthServerBackend: auth-server:8080
    cnClientApiServerUrl: client-api:8443
    cnClientApiBindIpAddresses: "*"
    cnLdapUrl: opendj:1636
    lbAddr: ""
    ldapServiceName: opendj
  image:
    repository: janssenproject/configuration-manager
    tag: 1.0.0_dev
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 300Mi
nginx-ingress:
  ingress:
    enabled: true
    path: /
    hosts:
    - demoexample.jans.io
    tls:
    - secretName: tls-certificate # DON'T change
      hosts:
      - demoexample.jans.io

opendj:
  service:
    ldapServiceName: opendj
  replicas: 1
  persistence:
    size: 5Gi
  image:
    repository: gluufederation/opendj
    tag: 1.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1500m
      memory: 2000Mi
    requests:
      cpu: 1500m
      memory: 2000Mi
persistence:
  image:
    repository: janssenproject/persistence-loader
    tag: 1.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 300Mi
auth-server:
  service:
    authServerServiceName: auth-server
  replicas: 1
  image:
    repository: janssenproject/auth-server
    tag: 1.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 2500m
      memory: 2500Mi
    requests:
      cpu: 2500m
      memory: 2500Mi
fido2:
  service:
    fido2ServiceName: fido2
  replicas: 1
  image:
    repository: janssenproject/fido2
    tag: 1.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
scim:
  service:
    scimServiceName: scim
  image:
    repository: janssenproject/scim
    tag: 1.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 1000m
      memory: 1000Mi
client-api:
  service:
    clientApiServerServiceName: client-api
  replicas: 1
  image:
    repository: janssenproject/client-api
    tag: 1.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 400Mi
    requests:
      cpu: 1000m
      memory: 400Mi
config-api:
  service:
    configApiServerServiceName: config-api
  replicas: 1
  image:
    repository: janssenproject/config-api
    tag: 1.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 400Mi
    requests:
      cpu: 1000m
      memory: 400Mi
auth-server-key-rotation:
  keysLife: 48
  image:
    repository: janssenproject/certmanager
    tag: 1.0.0_dev
    pullPolicy: Always
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 300Mi
