{{- if .Values.global.istio.ingress }}
# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-istio-scim-config
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.global.fqdn }}
  gateways:
  - {{ .Release.Name }}-global-gtw # can omit the namespace if gateway is in same namespace as virtual service.
  http:
  - name: {{ .Release.Name }}-istio-scim-config
    match:
    - uri:
        prefix: /.well-known/scim-configuration
    rewrite:
      uri: /scim/restv1/scim-configuration
    route:
      - destination:
          host: {{ .Values.global.scim.scimServiceName }}.{{.Release.Namespace}}.svc.cluster.local
          port:
            number: 8080
        weight: 100
  - name: {{ .Release.Name }}-istio-scim
    match:
    - uri:
        prefix: "/scim"
    route:
    - destination:
        host: {{ .Values.service.scimServiceName }}.{{.Release.Namespace}}.svc.cluster.local
        port:
          number: 8080
      weight: 100
{{- end }}
