
apiVersion: v2
name: persistence
version: 1.0.6
kubeVersion: ">=v1.21.0-0"
description: Job to generate data and initial config for Janssen Server persistence layer.
type: application
keywords:
  - persistence prep
home: https://jans.io
sources:
  - https://github.com/JanssenProject/jans/docker-jans-persistence-loader
maintainers:
  - name: Mohammad Abudayyeh
    email: support@jans.io
    url: https://github.com/moabu
icon: https://github.com/JanssenProject/jans/raw/main/docs/assets/logo/janssen_project_favicon_transparent_50px_50px.png
appVersion: "1.0.6"

