{{ if .Values.usrEnvs.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-user-custom-envs
  labels:
{{ include "auth-server-key-rotation.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.usrEnvs.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end}}